name: custom_map_markers
description: A package that turns runtime widgets into map marker icons.
version: 0.0.1
homepage: https://github.com/IbrahimTabba/custom_map_markers

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: 
  synchronized: 
  collection: 

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
